In [13]:
import numpy as np

In [14]:
#mendefinisikan bentuk environment yang memiliki 11 rows, dan 11 columns, sehingga memiliki 121 kemungkinan states (lokasi)
env_baris = 11
env_kolom = 11

#membuat array 3 dimensi dengan menggunakan numpy untuk menampung nilai Q
q_values = np.zeros((env_baris, env_kolom, 4))

In [15]:
#mendefinisikan action
aksi = ['atas', 'kanan', 'bawah', 'kiri']

In [16]:
#membuat array 2 dimensi untuk menapung reward
#array berisi 11 baris dan 11 kolom (sesuai dengan environment), dan diberi nilai -100

rewards = np.full((env_baris, env_kolom), -100.)
rewards [0, 5] = 100. #memberi nilai reward 100 pada goal


#menentukan lorong yang akan diberi reward -1
lorong = {}
lorong[1] = [i for i in range (1, 10)]
lorong[2] = [1, 7, 9]
lorong[3] = [i for i in range (1, 9)]
lorong[3].append(9)
lorong[4] = [3, 7]
lorong[5] = [i for i in range (11)]
lorong[6] = [5]
lorong[7] = [i for i in range (1, 10)]
lorong[8] = [3, 7]
lorong[9] = [i for i in range(11)]

#nested for untuk memberi nilai reward untuk tiap lorong
for index_baris in range(1, 10):
    for index_kolom in lorong[index_baris]:
        rewards[index_baris, index_kolom] = -1

#menampilkan reward
for baris in rewards:
    print(baris)


[[-100. -100. -100. -100. -100.  100. -100. -100. -100. -100. -100.]
 [-100. -100. -100. -100. -100. -100. -100. -100. -100. -100. -100.]
 [-100. -100. -100. -100. -100. -100. -100. -100. -100. -100. -100.]
 [-100. -100. -100. -100. -100. -100. -100. -100. -100. -100. -100.]
 [-100. -100. -100. -100. -100. -100. -100. -100. -100. -100. -100.]
 [-100. -100. -100. -100. -100. -100. -100. -100. -100. -100. -100.]
 [-100. -100. -100. -100. -100. -100. -100. -100. -100. -100. -100.]
 [-100. -100. -100. -100. -100. -100. -100. -100. -100. -100. -100.]
 [-100. -100. -100. -100. -100. -100. -100. -100. -100. -100. -100.]
 [-100. -100. -100. -100. -100. -100. -100. -100. -100. -100. -100.]
 [-100. -100. -100. -100. -100. -100. -100. -100. -100. -100. -100.]]
[-100. -100. -100. -100. -100.  100. -100. -100. -100. -100. -100.]
[-100.   -1.   -1.   -1.   -1.   -1.   -1.   -1.   -1.   -1. -100.]
[-100.   -1. -100. -100. -100. -100. -100.   -1. -100.   -1. -100.]
[-100.   -1.   -1.   -1.   -1.   -1.

In [ ]:
#non terminal state = kotak putih/yang nilainya -1
#terminal state = kotak hitam/yang nilaainya -100 & goal yang nilainya 100

#fungsi untuk menentukan menentukan apakah lokasi yang ditentukan adalah terminal state
def is_terminal_state(index_baris_saat_ini, index_kolom_saat_ini):
    if rewards[index_baris_saat_ini, index_kolom_saat_ini] == -1.:
        return False
    else:
        return True

#fungsi menentukan lokasi awal secara acak (yang non terminal state/kotak putih)
def mendapatkan_lokasi_awal():

    #mendapatkan baris acak
    index_baris_saat_ini = np.random.randint(env_baris)
    index_kolom_saat_ini = np.random.randint(env_kolom)

    #terus memilih baris dan kolom secara acak sampai ketemu non terminal state/kotak putih
    while is_terminal_state(index_baris_saat_ini, index_kolom_saat_ini):
        index_baris_saat_ini = np.random.randint(env_baris)
        index_kolom_saat_ini = np.random.randint(env_kolom)
    return index_baris_saat_ini, index_kolom_saat_ini

#mendefinisikan epsilon greedy algorithm
def mendapatkan_aksi_selanjutnya(index_baris_saat_ini, index_kolom_saat_ini, epsilon):

    """jika nilai yang dipilih secara acak antara 0 sampai 1 kurang dari nilai epsilon (90% atau 0,9), 
    maka pilih nilai yang paling menjanjikan dari tabel Q untuk keadaan ini"""
    if np.random.random() < epsilon:
        return np.argmax(q_values[index_baris_saat_ini, index_kolom_saat_ini])
    else:#10% nya memilih action secara random (untuk eksplorasi)
        return np.random.randint(4)

#mendefinisikan lokasi berikutnya setelah melakukan action yang dipilih
def mendapatkan_lokasi_selanjutnya(index_baris_saat_ini, index_kolom_saat_ini, index_aksi):
    index_baris_baru = index_baris_saat_ini
    index_kolom_baru = index_kolom_saat_ini
    if aksi[index_aksi] == 'atas' and index_baris_saat_ini > 0:
        index_baris_baru -= 1
    elif aksi[index_aksi] == 'kanan' and index_kolom_saat_ini < env_kolom -1:
        index_kolom_baru += 1
    elif aksi[index_aksi] == 'bawah' and index_baris_saat_ini < env_baris -1:
        index_baris_baru += 1
    elif aksi[index_aksi] == 'kiri' and index_kolom_saat_ini > 0:
        index_kolom_baru -= 1
    return index_baris_baru, index_kolom_baru

#fungsi untuk menentukan jalur terpendek yang dapat dilalui dari lokasi manapun yang diizinkan (lokasi yang kotak putih)
def mendapatkan_jalur_terpendek(mulai_index_baris, mulai_index_kolom):
    if is_terminal_state(mulai_index_baris, mulai_index_kolom):
        return[]
    else:
        index_baris_saat_ini, index_kolom_saat_ini = mulai_index_baris, mulai_index_kolom
        jalur_terpendek = []
        jalur_terpendek.append([index_baris_saat_ini, index_kolom_saat_ini])

        while not is_terminal_state(index_baris_saat_ini, index_kolom_saat_ini):
            index_aksi = mendapatkan_aksi_selanjutnya(index_baris_saat_ini, index_kolom_saat_ini, 1.)
            index_baris_saat_ini, index_kolom_saat_ini = mendapatkan_lokasi_selanjutnya(index_baris_saat_ini, index_kolom_saat_ini, index_aksi)
            jalur_terpendek.append([index_baris_saat_ini, index_kolom_saat_ini])
        return jalur_terpendek


In [ ]:
#mendefiniskan training parameter
epsilon = 0.9 #persentase waktu ketika kita harus mengambil tindakan terbaik (?)
discount_factor = 0.9 #discount factor future reward
learning_rate = 0.9 #mengontrol seberapa cepat agent untuk belajar

#menjalankan sebanyak 1000 episode
for episode in range (1000):

    #mendapatkan lokasi awal untuk episode ini (kotak putih)
    index_baris, index_kolom = mendapatkan_lokasi_awal()

    #terus melakukan action sampai mencapai terminal state (kotak hitam/hijau)
    while not is_terminal_state(index_baris, index_kolom):
        index_aksi = mendapatkan_aksi_selanjutnya(index_baris, index_kolom, epsilon)
        
        #menentukan aksi dan memilih keadaan selanjutnya (berpindah ke lokasi selanjutnya)
        index_baris_lama, index_kolom_lama = index_baris, index_kolom
        index_baris, index_kolom = mendapatkan_lokasi_selanjutnya(index_baris, index_kolom, index_aksi)
        
        #mendapatkan hadiah dan menghitung temporal difference setelah mencapai lokasi baru
        reward = rewards[index_baris, index_kolom]
        q_values_lama = q_values[index_baris_lama, index_kolom_lama, index_aksi]
        temporal_difference = reward + (discount_factor * np.max(q_values[index_baris, index_kolom])) - q_values_lama

        #update nilai q untuk state dan aksi sebelumnya setelah mencapai lokasi baru
        q_values_baru = q_values_lama + (learning_rate * temporal_difference)
        q_values[index_baris_lama, index_kolom_lama, index_aksi] = q_values_baru

print('Training selesai')

In [ ]:
print(mendapatkan_jalur_terpendek(3, 9))
print(mendapatkan_jalur_terpendek(4, 3))
print(mendapatkan_jalur_terpendek(9, 5))

In [ ]:
path = mendapatkan_jalur_terpendek(5, 2)
path.reverse()
print("")
print(path)